import Anouncment1 from '../assets/duyuru.png'
export const Data = [
    {
        id: '1',
        title: 'Duyuru 1',
        image: Anouncment1,
        content: 'Görselsiz duyuru. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?'
    },
    {
        id: '2',
        title: 'Duyuru 2',
        image: null, 
        content: 'Görselsiz duyuru. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?'
    },
    {
        id: '3',
        title: 'Duyuru 2',
        image: null, 
        content: 'Görselsiz duyuru. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?'
    },
    {
        id: '4',
        title: 'Duyuru 2',
        image: null, 
        content: 'Görselsiz duyuru. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?'
    },
    {
        id: '5',
        title: 'Duyuru 2',
        image: null, 
        content: 'Görselsiz duyuru. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?'
    },
    {
        id: '6',
        title: 'Duyuru 2',
        image: null, 
        content: 'Görselsiz duyuru. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?'
    },
    {
        id: '7',
        title: 'Duyuru 2',
        image: null, 
        content: 'Görselsiz duyuru. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores repudiandae, maxime doloribus veritatis facilis dolorem mollitia, commodi est non, libero eius minima voluptatum quasi! Voluptatum animi vitae quo consequatur nostrum?'
    },
];
